version: '3.9'

services:

  db:
    image: postgres:13-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo
    ports:
      - 5432:5432

  web:
    build: ./backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/foo
    depends_on:
      - db
    restart: on-failure