version: '3.9'

services:

  web-1:
    build: ./backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    restart: on-failure

  web-2:
    build: ./backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8001
    ports:
      - 8001:8001
    restart: on-failure