"""Add messages table

Revision ID: 36d11b3df023
Revises: a96ad4ed10d6
Create Date: 2023-05-08 19:49:29.904017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36d11b3df023'
down_revision = 'a96ad4ed10d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('sender_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('receiver_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'sender_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('messages_id_sender_id_created_at_desc_idx', 'messages', ['id', 'sender_id', sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('messages_id_sender_id_created_at_desc_idx', table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
