"""add users_id_name_last_login_desc_idx

Revision ID: a96ad4ed10d6
Revises: 00b35a8b35d0
Create Date: 2023-05-07 15:50:36.505118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96ad4ed10d6'
down_revision = '00b35a8b35d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'users_id_name_last_login_desc_idx',
        'users',
        ['id', 'name', sa.text('last_login DESC')],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('users_id_name_last_login_desc_idx', table_name='users')
    # ### end Alembic commands ###
